// packages/react/src/adapter.tsx
import { type Root, type Container, createRoot } from "react-dom/client";
import { Wrapper, type WrapperProperties } from "./wrapper";

export interface Adapter<Props extends Record<string | number | symbol, unknown>> {
    render(container: Container, wrapperProps: WrapperProperties, props: Props): void;
    destroy(): void;
}

export type PropertiesOf<T> = T extends new (...args: unknown[]) => Adapter<infer Props> ? Props : Record<never, unknown>;

export const getAdapter = <Props extends Record<string | number | symbol, unknown>>(Component: React.FC<Props>) => class implements Adapter<Props> {
    #root: Root | undefined;
    #container: Container | undefined;

    public render(container: Container, wrapperProps: WrapperProperties, props: Props) {
        if (container !== this.#container) {
            this.#cleanupPreviousRoot();
        }
        const root = this.#root ?? this.#createRoot(container);

        root.render(<Wrapper {...wrapperProps}><Component {...props} /></Wrapper>);
    }

    public destroy() {
        this.#cleanupPreviousRoot();
    }

    #createRoot(container: Container): Root {
        this.#container = container;
        this.#root = createRoot(container);
        return this.#root;
    }

    #cleanupPreviousRoot() {
        if (this.#root) {
            this.#root.unmount();
            this.#root = undefined;
            this.#container = undefined;
        }
    }
}

// packages/angular/src/react/adapter.ts
import { Component, ElementRef, HostBinding, NgZone, OnDestroy } from '@angular/core';
import type { Adapter, WrapperProperties } from '@tfa/react'

@Component({ template: '' })
export abstract class ReactAdapter<Props extends Record<string | number | symbol, unknown>> implements OnDestroy {
    @HostBinding('style.display') readonly display = 'contents';

    protected abstract readonly reactAdapter: Adapter<Props>;

    constructor(
        protected readonly elementRef: ElementRef,
        protected readonly zone: NgZone
    ) { }

    protected render(wrapperProps: WrapperProperties, props: Props) {
        this.zone.runOutsideAngular(() => this.reactAdapter.render(this.elementRef.nativeElement, wrapperProps, props));
    }

    protected getSafeCallback<Args extends Array<unknown>, Ret>(callback: (...args: Args) => Ret) {
        return (...args: Args) => this.zone.run(callback as never, undefined, args)
    }

    public ngOnDestroy(): void {
        this.zone.runOutsideAngular(() => this.reactAdapter.destroy());
    }
}
